# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.3.dev0+g6bbb25e.d20221007'
__version_tuple__ = version_tuple = (0, 1, 3, 'dev0', 'g6bbb25e.d20221007')
