# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.2.dev75+gdd97666.d20220930'
__version_tuple__ = version_tuple = (0, 1, 2, 'dev75', 'gdd97666.d20220930')
