name: napari-tomotwin
channels:
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - napari=0.4.17
  - pyqt
  - cuml=23.12
  - cuda-version=11.8
  - pip
  - pip:
      - napari-boxmanager
      - napari-tomotwin
      - napari-clusters-plotter@git+https://github.com/BiAPoL/napari-clusters-plotter.git@5e937dc

