name: tomotwin
channels:
  - nvidia
  - pytorch
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - pytorch[version='>=2.1']
  - torchvision
  - pandas
  - scipy
  - numpy
  - matplotlib
  - pytables
  - cuml=24.08
  - cuda-version=11.8
  - protobuf[version='>3.20']
  - tensorboard
  - optuna
  - pytorch-metric-learning
  - pip
  - pip:
      - mysql-connector-python # conda did not provide version 8.3. Version 8.0.3 failed with cuml 23.10
  #    - tomotwin-cryoet

