name: tomotwin
channels:
  - nvidia
  - pytorch
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - pytorch[version='>=2.1']
  - torchvision
  - pandas[version='<2']
  - scipy
  - numpy
  - matplotlib
  - pytables
  - cuml=23.12
  - cuda-version=11.8
  - protobuf[version='>3.20']
  - tensorboard
  - optuna
  #- mysql-connector-python # we need it for optuna, but it does not go together with cuml 23.12
  - pytorch-metric-learning
  - pip
  - pip:
      - mysql-connector-python
  #    - tomotwin-cryoet

