name: tomotwin
channels:
  - nvidia
  - pytorch-nightly
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - pandas[version='<2']
  - scipy
  - numpy
  - matplotlib
  - pytables
  - cuml=23.04
  - cudatoolkit=11.8
  - protobuf[version='>3.20']
  - tensorboard
  - optuna
  - mysql-connector-python
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/nightly/cu118
      - torch==2.1.0.dev20230822+cu118
      - torchvision==0.16.0.dev20230822
      - tomotwin-cryoet

