name: napari-tomotwin
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - napari=0.4.17
  - pyqt
  - pip
  - pip:
      - napari-boxmanager
      - napari-tomotwin
      - napari-clusters-plotter@git+https://github.com/BiAPoL/napari-clusters-plotter.git@095d9e8

