name: tomotwin
channels:
  - conda-forge
  - pytorch
  - rapidsai
  - nvidia
  - defaults
dependencies:
  - pytorch==1.13.1
  - torchvision
  - pandas[version='<2']
  - scipy
  - numpy
  - matplotlib
  - pytables
  - cuml=23.04
  - cudatoolkit=11.8
  - protobuf[version='>3.20']
  - tensorboard
  - optuna
  - mysql-connector-python
